### ISSUE TITLE
Missing documentation for building / using this code

### ISSUE THREAD

**Issue by samcom12** [NHERI-SimCenter/HydroUQ#44]
Hi, Wanted to try out this code but couldn't get any doc for installation instruction and all.
When can we expect the same?

**Comment by bhajay** [comment]
@samcom12 : Not sure how we missed this. An updated version is coming out in the next few days (before the end of Feb) including new documentation, installer, and also instructions to compile from source.

**Comment by samcom12** [comment]
Thanks @bhajay Will try it
